assets/js/_config.js, assets/js/actions/_event.js, src/Constant/ErrorCodeConstant.php, src/EventSubscriber/ExceptionsSubscriber.php, src/Security/LoginFormAuthenticator.php, tests/Feature/Api/DatabaseControllerTest.php, tests/Feature/Api/GraphControllerTest.php, tests/Feature/Api/UserControllerTest.php
=> hot fix/LE-102

assets/js/components/_js-grid-table.js, assets/styles/component/_js-grid-table.scss
=> LE-107 Can't access the page in middle of home page table #107

assets/js/actions/_database-actions.js, assets/js/pages/database/form.js, assets/js/pages/database/tables.js, src/Controller/Api/DatabaseController.php
add delete table feature, show delete confirmation modal when delete a table or column
=> #LE-148 #LE-114

assets/js/components/_log-detail-sidebar.js, assets/js/components/widget/_widget-management.js, assets/styles/component/_log_detail_sidebar.scss
=> Feature/LE-160 explore view: make details view wider

assets/js/components/_sidebar.js, assets/js/components/widget/_widget-management.js
=> Feature/LE-161 Select or create new images for menu items - Move "Widgets" to dashboard area

assets/js/pages/index/index.js
=> hotfix/LE-180 Bug: Real time button does not work if left menu 

assets/js/components/widget/_doughnut-pie-chart.js, assets/js/components/widget/_responsive-grid-layout.js, assets/js/components/widget/_widget-table.js, assets/js/pages/index/dashboard.js
=> feature/LE-214 Interactive Widgets 

assets/js/components/widget/_widget-management.js
=> hotfix/LOG-19 LIKE search for timestamp field not possible

cypress/integration/test/database.js, src/Repository/UserRepository.php
=> fix api authentication error

assets/app.js, assets/js/components/_button.js, assets/js/components/_content-header.js, assets/js/components/_data-table.js, assets/js/components/_delete-modal.js, assets/js/components/_icon.js, assets/js/components/_modal.js, assets/js/components/_nav-user.js, assets/js/components/_navbar.js, assets/js/components/_table.js, assets/js/components/_toast.js, assets/js/components/index.js, assets/js/pages/user/list.js, assets/js/utils.js, assets/vendor/theme.min.js, templates/base.html.twig, webpack.config.js
=> Feature/LOG-10 Update user page

assets/js/components/_change-password.js, assets/js/components/_user-profile.js
=> Feature/LOG-52 [UI improvement] Change profile card size to col-5

assets/js/pages/user/profile.js
=> LOG-56  [UI Issue] Expand viewport

assets/styles/_logexplorer.scss
=> LOG-57  Give the topbar a z-index of 1 

assets/js/pages/database/table-details.js
=> LOG-58 [UI Issue] Change wording on deleting dialogue

assets/js/pages/export/list.js
=> LOG-8 Exports Table

assets/js/components/_advanced-search.js, assets/js/components/_card-tools.js, assets/js/components/_filter-date.js, assets/js/components/_filter-text.js, assets/js/components/_log-view-table-setting-modal.js, assets/js/components/_log-view-table.js, assets/js/components/_log-views-list.js, assets/js/components/_uplot-chart.js, assets/js/pages/export/list.js, assets/js/pages/index/index.js, assets/styles/_logexplorer.scss, assets/styles/component/_advanced-search.scss, assets/styles/component/_filter-text.scss, assets/styles/component/_log-views-list.scss, assets/styles/pages/index.scss
=> LOG-68 Explore advance search pannel 

assets/js/components/_log-detail-sidebar.js, assets/js/components/_log-views-list.js
=> LOG-71 Wrong wording on Datatable select

assets/js/pages/alerts/form.js
=> Feature/LOG-31 Display error message  when input get negative value

assets/js/components/_change-password.js, assets/styles/_logexplorer.scss
=> Feature/log-33 Enhancement hide and show password

assets/js/components/_content-header.js, assets/js/components/_dashboard-content.js, assets/js/components/widget/_chart.js, assets/js/components/widget/_responsive-grid-layout.js, assets/js/components/widget/_table.js, assets/js/pages/alerts/list.js, assets/js/pages/user/list.js
=> Feature/LOG-73 Revert filter panel in dasboard page

assets/js/pages/export/list.js
=> Feature/LOG-76 [UI Issue] Correction of wording "No Exports found"

assets/js/components/_widget-list-modal.js, assets/js/components/widget/_widget-list.js, assets/js/pages/index/dashboard.js, assets/styles/component/_widget-list-modal.scss
=> Feature/LOG-72 [UI Enhancement] Change behavior of adding a widget

assets/js/components/_create-dashboard.js
=> Feature/LOG-63 

assets/js/components/_change-password.js, assets/js/components/_input-password.js, assets/js/components/index.js, assets/js/pages/security/_reset-password-form.js, assets/js/pages/security/reset-password.js, assets/styles/_logexplorer.scss
=> feature/LOG-88 Forgot password screen
